# Generated by Django 5.0.7 on 2024-08-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0003_unverifieduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
