# Generated by Django 5.0.7 on 2024-08-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0005_customuser_dob_unverifieduser_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dob',
        ),
    ]
