# Generated by Django 5.0.7 on 2024-08-14 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0006_remove_customuser_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unverifieduser',
            name='dob',
        ),
    ]
