# Generated by Django 5.0.7 on 2024-08-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0007_remove_unverifieduser_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unverifieduser',
            name='dob',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
